### PR TITLE
Fix _compute_hash if content received is bytes

### PR DESCRIPTION
**Pull request by rebkwok**
Accommodate `content` being `str` or `bytes`

### CODE REVIEW

**Comment by rebkwok** [comment]
@pauricthelodger Mind taking a quick look at this one?

**Comment by rebkwok** [comment]
@pauricthelodger ContentFile can operate on either according to Django docs. Django by default opens a FileField content as bytes, but it seemed prudent to check and allow for either.

**Comment by pauricthelodger** [comment]
Cool, makes sense, cheers =)

**Comment by rebkwok** [comment]
Fixes #8

**Pull request merged**
